module Language.Lsl.Internal.VersionString (versionString) where

import Data.Version(showVersion)
import Paths_LSLForge(version)  -- generated by cabal

versionString :: String
versionString = showVersion version
